module.exports = [
  { slug: "roof-leak-repairs", title: "Roof leak repairs", intro: "A leak needs a route: understand where water enters, then focus the repair on the weak point.", points: ["Discuss where water, drips, or stains first appeared.", "Consider junctions such as chimneys, valleys, ridges, and flashing.", "Share photographs only where they can be taken safely."], verify: "Management to confirm the inspection scope, form route, and any response wording.", image: "/images/projects/roof-work-04.jpeg", imageAlt: "East Sussex Roofing van outside a Brighton terrace", imageNote: "A local roof context helps put the first conversation in focus." },
  { slug: "strip-and-rebatten", title: "Strip and rebatten", intro: "When a roof covering needs to come off, a strip and rebatten project creates a clearer view of the layers beneath.", points: ["Discuss the condition of the existing tiles or slates and what prompted the work.", "Review battens and the underlay as the roof is opened up, subject to safe access.", "Agree the replacement covering, edge details, waste handling, and project record before work begins."], verify: "Management to confirm the full strip-and-rebatten scope, materials, guarantees, and any structural work included.", image: "/images/projects/roof-work-03.jpeg", imageAlt: "Roofing work in progress on a Brighton and Hove property", imageNote: "A work-in-progress photograph can show the project stage without pretending to be a completed case study." },
  { slug: "tile-and-slate-repairs", title: "Tile and slate repairs", intro: "Repair or replace damaged roof coverings where the problem can be identified and safely accessed.", points: ["Broken, slipped, or missing units can each point to a different repair conversation.", "Matching existing materials may need to take type, colour, age, and availability into account.", "Do not climb onto the roof to inspect from an unsafe position."], verify: "Management to confirm available materials and the exact repair scope." },
  { slug: "ridge-verge-valley-repairs", title: "Ridge, verge and valley repairs", intro: "Roof edges and junctions shed water; failed details can become routes for leaks.", points: ["Describe whether the issue is along the ridge, sloping verge, or valley.", "Photograph displaced or cracked detail only from a safe position.", "The surrounding covering may be relevant to the repair plan."], verify: "Management to confirm the materials and methods it offers." },
  { slug: "chimney-and-leadwork-repairs", title: "Chimney and leadwork repairs", intro: "Chimneys and flashing are detail work, and small failures can lead water into the roof or wall.", points: ["Note where water appears in relation to the chimney.", "Mention whether the chimney is in use, capped, or no longer used if known.", "Keep outside photographs to safe ground or window views."], verify: "Management to confirm leadwork scope, access requirements, and approved claims." },
  { slug: "flat-roof-repairs", title: "Flat-roof repairs", intro: "The right repair depends on how the flat-roof covering is failing and how water is draining.", points: ["Describe cracking, bubbling, tears, worn seams, or standing water.", "Share the age and material of the roof if known.", "The inspection may distinguish a local repair from a wider replacement need."], verify: "Management to confirm material types, repair limits, and any warranties.", image: "/images/projects/roof-work-01.jpeg", imageAlt: "Flat roof surface viewed from above over a Brighton neighbourhood", imageNote: "The existing site image shows why surface condition and roof junctions need to be considered together." },
  { slug: "drone-surveys", title: "Drone surveys", intro: "Aerial photography can help document roof areas that are difficult or disproportionate to access from the ground.", points: ["Use a drone survey only where it is safe, lawful, proportionate, and genuinely useful.", "Capture clear stills or video of roof surfaces, junctions, coverings, and surrounding context.", "Share the relevant evidence with the project record rather than using aerial imagery as a substitute for every inspection."], verify: "Management to confirm pilot competence, operating permissions, privacy controls, weather limits, retention, and whether this service is actually offered.", image: "/images/projects/roof-work-01.jpeg", imageAlt: "Roof surface and surrounding Brighton neighbourhood viewed from above", imageNote: "This existing aerial-style project photograph demonstrates the kind of context a survey record can provide; it is not presented as proof of a drone operation." },
  { slug: "guttering-fascias-soffits", title: "Guttering, fascias and soffits", intro: "A working rainwater system helps move water away from the roof and walls.", points: ["Describe sagging runs, leaking joints, blockages, or water running down a wall.", "Note which side of the property is affected.", "Ground-level photographs are often useful if they can be taken safely."], verify: "Management to confirm cleaning, repair, and replacement services offered." },
  { slug: "roof-inspections", title: "Roof inspections", intro: "An inspection can give a clearer picture of visible condition and priorities for repair or maintenance.", points: ["Share the concern you want the inspection to address.", "Explain which roof, loft, or access points are available.", "An inspection is not automatically a structural engineering assessment."], verify: "Management to confirm inspection deliverables, report format, and limitations." },
  { slug: "new-roofs-and-re-roofing", title: "New roofs and re-roofing", intro: "When repair is no longer practical, replacing a roof covering becomes a larger planned project.", points: ["The condition of the existing covering and structure affects the scope.", "Material choices, edge details, access, and waste handling should be discussed clearly.", "A re-roofing page should publish only verified options and project claims."], verify: "Management to confirm that this service is offered, material options, guarantees, and project process." }
];
